sudo: required
services:
- docker

before_install:
- docker pull sumankhanal/texlive-2019


script:
- docker run --name tmp sumankhanal/texlive-2019 /bin/bash -c "cd ~; wget https://raw.githubusercontent.com/BeanLiu1994/njuthesis-nju-thesis-template/travis_test/command.sh;chmod +x command.sh; ./command.sh"
- docker cp tmp:/root/njuthesis-nju-thesis-template/sample.pdf ./

deploy:
  provider: releases
  api_key:
    secure: lN3Sjkzt0BGEYgOBUlnbYR0K0RB3U5XI2BD0/ZpjQGh31XNZ7rbtFocZGgFZab8W+YNnUtmI/qmhHDcqtDmQ4qYQ05Q5i0DWjSJ0gduyVNgjyARRLNvoNYAchLWLcvq/RtH8RsMJFx2Q7oukFgf2KOOtAfGJx3tA327LLOaLSVbtxZ2feD1bYZq/LGS5ImB1Na8j29rUkb+X1D7xplIc0X/QxInA25SY54RGpn7u3YGigN9XCyFNs09fYHxtkZaN2cDX3T1tKJKEiKq1a0UGGVapgrI6q7lGT9UP22SiotlorHVp+BeNYySMxDXWMM2qMRGRosWJrKkUx9Z8zAMAeV1cl8KEaUGTFxIxmhlwl8c0nqiYj7EGDXObfbIESyW25AslBsDkZA4DsAU3uFK2C9k65jNzRmIP8EDsr4PN/pesCBVoPBwGj5WQRjCbSFRZxifYFLBqEqCPX3mdQMKdJwjY3tPUfiNh3kFfIGiAm0ADvBkfghpq3NWcIfAu+z0gAcFp0I36mZXc4jzW2HzyeBxF0DDX6RC8R9HYGHQOxPRSqE8U3OnIEWY67bAfn0M0X1o9hqNIloU2ufkB1uYVZa8cGvy7cpOGTzM+YkvcyI+3YiHnUcUUqmX/7YzMg26Zk1TtzZngKcCCajO5pbqiRoxFYXjGHLmT07NUiy2d1/k=
  file: sample.pdf
  skip_cleanup: true
  draft: true
  on:
    repo: BeanLiu1994/njuthesis-nju-thesis-template